In [1]:
import pandas as pd
import numpy as np

print("Python setup is working!")

Python setup is working!

In [2]:
customers = pd.read_excel("Customer_Sales_Intelligence_Dataset.xlsx", sheet_name="Customers")
products = pd.read_excel("Customer_Sales_Intelligence_Dataset.xlsx", sheet_name="Products")
orders = pd.read_excel("Customer_Sales_Intelligence_Dataset.xlsx", sheet_name="Orders")

In [3]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
0,ORD-100001,2025-10-17,CUST-0662,PROD-048,5,0.00,16624.85,5083.99,Nagad,Delivered
1,ORD-100002,2025-04-21,CUST-1425,PROD-009,2,0.20,7495.87,1845.95,Cash on Delivery,Delivered
2,ORD-100003,2025-05-19,CUST-0272,PROD-039,4,0.05,94402.49,21615.55,Card,Delivered
3,ORD-100004,2025-11-02,CUST-1004,PROD-059,1,0.00,4184.55,1013.89,Nagad,Delivered
4,ORD-100005,2025-06-25,CUST-0269,PROD-003,4,0.20,88857.95,13593.28,Card,Delivered

In [4]:
orders.shape

(10005, 10)

In [5]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 10005 entries, 0 to 10004
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10005 non-null  str
 1   Order_Date      10005 non-null  datetime64[us]
 2   Customer_ID     10005 non-null  str
 3   Product_ID      10005 non-null  str
 4   Quantity        10005 non-null  int64
 5   Discount        9980 non-null   float64
 6   Sales           10005 non-null  float64
 7   Profit          10005 non-null  float64
 8   Payment_Method  9993 non-null   str
 9   Order_Status    10005 non-null  str
dtypes: datetime64[us](1), float64(3), int64(1), str(5)
memory usage: 1.2 MB

In [6]:
orders.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
Product_ID         0
Quantity           0
Discount          25
Sales              0
Profit             0
Payment_Method    12
Order_Status       0
dtype: int64

In [8]:
orders.duplicated().sum()

np.int64(5)

In [9]:
orders.describe()

,Order_Date,Quantity,Discount,Sales,Profit
count,10005,10005.000000,9980.000000,10005.000000,10005.000000
mean,2025-07-02 15:32:47.856072,2.388606,0.064975,60943.502502,8498.432694
min,2025-01-01 00:00:00,1.000000,0.000000,0.000000,0.000000
25%,2025-04-01 00:00:00,1.000000,0.000000,8634.390000,1657.950000
50%,2025-07-04 00:00:00,2.000000,0.050000,25445.040000,4415.510000
75%,2025-10-02 00:00:00,4.000000,0.100000,71244.380000,10675.160000
max,2025-12-31 00:00:00,5.000000,0.200000,599462.400000,106294.590000
std,NaN,1.409296,0.063197,90166.649884,11446.160237

In [10]:
orders.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity',
       'Discount', 'Sales', 'Profit', 'Payment_Method', 'Order_Status'],
      dtype='str')

In [11]:
orders.nunique()

Order_ID          10000
Order_Date          365
Customer_ID        1498
Product_ID          100
Quantity              5
Discount              5
Sales              2143
Profit             9093
Payment_Method        4
Order_Status          3
dtype: int64

In [12]:
orders[orders.duplicated(keep=False)]

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
0,ORD-100001,2025-10-17,CUST-0662,PROD-048,5,0.00,16624.85,5083.99,Nagad,Delivered
1,ORD-100002,2025-04-21,CUST-1425,PROD-009,2,0.20,7495.87,1845.95,Cash on Delivery,Delivered
2,ORD-100003,2025-05-19,CUST-0272,PROD-039,4,0.05,94402.49,21615.55,Card,Delivered
3,ORD-100004,2025-11-02,CUST-1004,PROD-059,1,0.00,4184.55,1013.89,Nagad,Delivered
4,ORD-100005,2025-06-25,CUST-0269,PROD-003,4,0.20,88857.95,13593.28,Card,Delivered
10000,ORD-100001,2025-10-17,CUST-0662,PROD-048,5,0.00,16624.85,5083.99,Nagad,Delivered
10001,ORD-100002,2025-04-21,CUST-1425,PROD-009,2,0.20,7495.87,1845.95,Cash on Delivery,Delivered
10002,ORD-100003,2025-05-19,CUST-0272,PROD-039,4,0.05,94402.49,21615.55,Card,Delivered
10003,ORD-100004,2025-11-02,CUST-1004,PROD-059,1,0.00,4184.55,1013.89,Nagad,Delivered
10004,ORD-100005,2025-06-25,CUST-0269,PROD-003,4,0.20,88857.95,13593.28,Card,Delivered

In [13]:
orders = orders.drop_duplicates()

In [14]:
orders.duplicated().sum()

np.int64(0)

In [15]:
orders.shape

(10000, 10)

In [16]:
orders[orders["Discount"].isnull()]

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
670,ORD-100671,2025-05-11,CUST-0767,PROD-075,5,NaN,25304.44,4644.46,Card,Delivered
741,ORD-100742,2025-12-03,CUST-0458,PROD-006,4,NaN,78996.56,9011.27,Cash on Delivery,Delivered
1001,ORD-101002,2025-04-18,CUST-0106,PROD-092,3,NaN,23743.99,5582.28,Card,Delivered
1144,ORD-101145,2025-01-23,CUST-1130,PROD-040,3,NaN,7067.81,2250.63,bKash,Delivered
2439,ORD-102440,2025-02-07,CUST-0736,PROD-023,1,NaN,13929.59,3744.25,Nagad,Delivered
2784,ORD-102785,2025-02-15,CUST-0240,PROD-001,2,NaN,110979.82,12728.61,Nagad,Delivered
2898,ORD-102899,2025-09-12,CUST-0830,PROD-060,2,NaN,13871.36,2620.57,Card,Delivered
2969,ORD-102970,2025-10-11,CUST-1260,PROD-016,2,NaN,19778.72,7067.59,bKash,Delivered
2976,ORD-102977,2025-01-29,CUST-0720,PROD-008,5,NaN,514423.44,53064.63,Cash on Delivery,Delivered
3385,ORD-103386,2025-10-04,CUST-1182,PROD-003,1,NaN,24991.30,3218.78,bKash,Delivered
3989,ORD-103990,2025-10-19,CUST-0794,PROD-062,4,NaN,239224.90,24353.32,Cash on Delivery,Delivered
4259,ORD-104260,2025-12-07,CUST-0647,PROD-060,4,NaN,23581.31,4148.68,bKash,Delivered
4340,ORD-104341,2025-10-13,CUST-0609,PROD-053,2,NaN,26725.97,3639.34,Nagad,Delivered
5620,ORD-105621,2025-03-24,CUST-0499,PROD-046,5,NaN,0.00,0.00,bKash,Returned
6016,ORD-106017,2025-09-01,CUST-1417,PROD-097,4,NaN,10884.00,3553.09,bKash,Delivered
6461,ORD-106462,2025-01-21,CUST-1078,PROD-005,4,NaN,0.00,0.00,Card,Cancelled
6914,ORD-106915,2025-01-02,CUST-1013,PROD-096,1,NaN,17632.36,3783.67,bKash,Delivered
6990,ORD-106991,2025-03-17,CUST-1356,PROD-042,5,NaN,309408.44,24276.47,Card,Delivered
7206,ORD-107207,2025-04-13,CUST-1466,PROD-036,3,NaN,5550.01,1853.19,bKash,Delivered
7597,ORD-107598,2025-02-03,CUST-0323,PROD-005,4,NaN,0.00,0.00,bKash,Returned
7643,ORD-107644,2025-11-27,CUST-0065,PROD-012,2,NaN,40980.78,3816.09,bKash,Delivered
7747,ORD-107748,2025-07-01,CUST-0864,PROD-021,3,NaN,4448.04,1414.90,Card,Delivered
8010,ORD-108011,2025-01-11,CUST-0016,PROD-050,1,NaN,95475.20,11149.96,Nagad,Delivered
8097,ORD-108098,2025-10-13,CUST-0679,PROD-079,2,NaN,8328.56,1705.52,Card,Delivered
8627,ORD-108628,2025-08-05,CUST-0560,PROD-097,5,NaN,13605.00,3923.49,Card,Delivered

In [17]:
orders[orders["Payment_Method"].isnull()]

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
802,ORD-100803,2025-01-11,CUST-0855,PROD-033,2,0.00,6817.88,1634.34,NaN,Delivered
846,ORD-100847,2025-06-08,CUST-0115,PROD-080,2,0.00,0.00,0.00,NaN,Cancelled
909,ORD-100910,2025-08-15,CUST-0196,PROD-058,5,0.00,82508.30,9175.40,NaN,Delivered
1063,ORD-101064,2025-04-29,CUST-1186,PROD-007,2,0.10,150663.46,16615.15,NaN,Delivered
1974,ORD-101975,2025-09-19,CUST-1151,PROD-094,4,0.00,60518.64,12833.36,NaN,Delivered
3696,ORD-103697,2025-01-28,CUST-0672,PROD-045,4,0.00,92599.32,12668.79,NaN,Delivered
4511,ORD-104512,2025-10-05,CUST-0134,PROD-058,1,0.10,14851.49,1747.79,NaN,Delivered
5974,ORD-105975,2025-01-23,CUST-1210,PROD-030,1,0.00,4557.32,1660.17,NaN,Delivered
6232,ORD-106233,2025-08-06,CUST-0511,PROD-012,1,0.15,17416.83,1333.09,NaN,Delivered
8648,ORD-108649,2025-10-27,CUST-0383,PROD-037,1,0.10,2726.65,823.69,NaN,Delivered
9402,ORD-109403,2025-02-28,CUST-0683,PROD-053,1,0.05,14935.10,1876.09,NaN,Delivered
9750,ORD-109751,2025-05-09,CUST-0928,PROD-002,1,0.05,16580.65,2752.00,NaN,Delivered

In [18]:
orders["Discount"] = orders["Discount"].fillna(0)
orders["Payment_Method"] = orders["Payment_Method"].fillna("Unknown")

In [19]:
orders.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Discount          0
Sales             0
Profit            0
Payment_Method    0
Order_Status      0
dtype: int64

In [20]:
orders.dtypes

Order_ID                     str
Order_Date        datetime64[us]
Customer_ID                  str
Product_ID                   str
Quantity                   int64
Discount                 float64
Sales                    float64
Profit                   float64
Payment_Method               str
Order_Status                 str
dtype: object

In [22]:
orders[['Quantity', 'Discount', 'Sales', 'Profit']].describe()

           Quantity      Discount          Sales         Profit
count  10000.000000  10000.000000   10000.000000   10000.000000
mean       2.388200      0.064800   60952.817682    8498.366644
std        1.409148      0.063181   90183.678539   11447.667887
min        1.000000      0.000000       0.000000       0.000000
25%        1.000000      0.000000    8634.390000    1657.800000
50%        2.000000      0.050000   25445.040000    4414.965000
75%        4.000000      0.100000   71171.067500   10667.990000
max        5.000000      0.200000  599462.400000  106294.590000

In [23]:
orders[~orders['Discount'].between(0, 1)]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Discount, Sales, Profit, Payment_Method, Order_Status]
Index: []

In [24]:
orders[orders['Quantity'] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Discount, Sales, Profit, Payment_Method, Order_Status]
Index: []

In [25]:
orders[orders['Sales'] <= 0]

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
5,ORD-100006,2025-12-14,CUST-0821,PROD-092,2,0.00,0.0,0.0,Cash on Delivery,Cancelled
33,ORD-100034,2025-12-17,CUST-0422,PROD-036,2,0.00,0.0,0.0,Card,Cancelled
35,ORD-100036,2025-10-04,CUST-1043,PROD-060,4,0.10,0.0,0.0,bKash,Cancelled
84,ORD-100085,2025-05-20,CUST-0863,PROD-039,4,0.15,0.0,0.0,bKash,Cancelled
100,ORD-100101,2025-12-19,CUST-0660,PROD-038,1,0.00,0.0,0.0,bKash,Cancelled
...,...,...,...,...,...,...,...,...,...,...
9926,ORD-109927,2025-06-08,CUST-0095,PROD-074,4,0.10,0.0,0.0,Cash on Delivery,Cancelled
9936,ORD-109937,2025-01-03,CUST-0935,PROD-049,5,0.10,0.0,0.0,Nagad,Returned
9963,ORD-109964,2025-10-05,CUST-1377,PROD-070,1,0.00,0.0,0.0,Cash on Delivery,Cancelled
9965,ORD-109966,2025-09-18,CUST-0598,PROD-024,4,0.00,0.0,0.0,Cash on Delivery,Returned
9989,ORD-109990,2025-04-15,CUST-0462,PROD-082,5,0.05,0.0,0.0,bKash,Cancelled

In [26]:
orders[['Quantity', 'Discount', 'Sales', 'Profit']].describe()

           Quantity      Discount          Sales         Profit
count  10000.000000  10000.000000   10000.000000   10000.000000
mean       2.388200      0.064800   60952.817682    8498.366644
std        1.409148      0.063181   90183.678539   11447.667887
min        1.000000      0.000000       0.000000       0.000000
25%        1.000000      0.000000    8634.390000    1657.800000
50%        2.000000      0.050000   25445.040000    4414.965000
75%        4.000000      0.100000   71171.067500   10667.990000
max        5.000000      0.200000  599462.400000  106294.590000

In [27]:
orders[~orders['Discount'].between(0, 1)]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Discount, Sales, Profit, Payment_Method, Order_Status]
Index: []

In [28]:
orders[orders['Quantity'] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Discount, Sales, Profit, Payment_Method, Order_Status]
Index: []

In [29]:
orders[orders['Sales'] <= 0]

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
5,ORD-100006,2025-12-14,CUST-0821,PROD-092,2,0.00,0.0,0.0,Cash on Delivery,Cancelled
33,ORD-100034,2025-12-17,CUST-0422,PROD-036,2,0.00,0.0,0.0,Card,Cancelled
35,ORD-100036,2025-10-04,CUST-1043,PROD-060,4,0.10,0.0,0.0,bKash,Cancelled
84,ORD-100085,2025-05-20,CUST-0863,PROD-039,4,0.15,0.0,0.0,bKash,Cancelled
100,ORD-100101,2025-12-19,CUST-0660,PROD-038,1,0.00,0.0,0.0,bKash,Cancelled
...,...,...,...,...,...,...,...,...,...,...
9926,ORD-109927,2025-06-08,CUST-0095,PROD-074,4,0.10,0.0,0.0,Cash on Delivery,Cancelled
9936,ORD-109937,2025-01-03,CUST-0935,PROD-049,5,0.10,0.0,0.0,Nagad,Returned
9963,ORD-109964,2025-10-05,CUST-1377,PROD-070,1,0.00,0.0,0.0,Cash on Delivery,Cancelled
9965,ORD-109966,2025-09-18,CUST-0598,PROD-024,4,0.00,0.0,0.0,Cash on Delivery,Returned
9989,ORD-109990,2025-04-15,CUST-0462,PROD-082,5,0.05,0.0,0.0,bKash,Cancelled

In [30]:
orders[orders['Profit'] < 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Discount, Sales, Profit, Payment_Method, Order_Status]
Index: []

In [31]:
orders.duplicated().sum()

np.int64(0)

In [32]:
orders['Order_ID'].duplicated().sum()

np.int64(0)

In [33]:
orders['Order_ID'].duplicated().sum()

np.int64(0)

In [34]:
orders['Payment_Method'].value_counts()

Payment_Method
bKash               3035
Card                2789
Cash on Delivery    2315
Nagad               1849
Unknown               12
Name: count, dtype: int64

In [35]:
orders['Order_Status'].value_counts()

Order_Status
Delivered    9120
Cancelled     496
Returned      384
Name: count, dtype: int64

In [36]:
orders.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Discount          0
Sales             0
Profit            0
Payment_Method    0
Order_Status      0
dtype: int64

In [37]:
orders.shape

(10000, 10)

In [38]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10000 non-null  str
 1   Order_Date      10000 non-null  datetime64[us]
 2   Customer_ID     10000 non-null  str
 3   Product_ID      10000 non-null  str
 4   Quantity        10000 non-null  int64
 5   Discount        10000 non-null  float64
 6   Sales           10000 non-null  float64
 7   Profit          10000 non-null  float64
 8   Payment_Method  10000 non-null  str
 9   Order_Status    10000 non-null  str
dtypes: datetime64[us](1), float64(3), int64(1), str(5)
memory usage: 1.2 MB

In [39]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
0,ORD-100001,2025-10-17,CUST-0662,PROD-048,5,0.00,16624.85,5083.99,Nagad,Delivered
1,ORD-100002,2025-04-21,CUST-1425,PROD-009,2,0.20,7495.87,1845.95,Cash on Delivery,Delivered
2,ORD-100003,2025-05-19,CUST-0272,PROD-039,4,0.05,94402.49,21615.55,Card,Delivered
3,ORD-100004,2025-11-02,CUST-1004,PROD-059,1,0.00,4184.55,1013.89,Nagad,Delivered
4,ORD-100005,2025-06-25,CUST-0269,PROD-003,4,0.20,88857.95,13593.28,Card,Delivered

In [40]:
orders.describe()

,Order_Date,Quantity,Discount,Sales,Profit
count,10000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-07-02 15:17:51.360000,2.388200,0.064800,60952.817682,8498.366644
min,2025-01-01 00:00:00,1.000000,0.000000,0.000000,0.000000
25%,2025-04-01 00:00:00,1.000000,0.000000,8634.390000,1657.800000
50%,2025-07-04 00:00:00,2.000000,0.050000,25445.040000,4414.965000
75%,2025-10-02 00:00:00,4.000000,0.100000,71171.067500,10667.990000
max,2025-12-31 00:00:00,5.000000,0.200000,599462.400000,106294.590000
std,NaN,1.409148,0.063181,90183.678539,11447.667887

In [41]:
total_orders = orders['Order_ID'].nunique()
total_sales = orders['Sales'].sum()
total_profit = orders['Profit'].sum()
aov = total_sales / total_orders

print("Total Orders:", total_orders)
print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Average Order Value:", aov)

Total Orders: 10000
Total Sales: 609528176.8199999
Total Profit: 84983666.44
Average Order Value: 60952.81768199999

In [42]:
orders.groupby('Order_Status')[['Sales', 'Profit']].sum()

                     Sales       Profit
Order_Status
Cancelled     0.000000e+00         0.00
Delivered     6.095282e+08  84983666.44
Returned      0.000000e+00         0.00

In [43]:
orders['Order_Status'].value_counts()

Order_Status
Delivered    9120
Cancelled     496
Returned      384
Name: count, dtype: int64

In [44]:
orders.groupby('Payment_Method').agg(
    Orders=('Order_ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
).sort_values('Sales', ascending=False)

                  Orders         Sales       Profit
Payment_Method
bKash               3035  1.825643e+08  25369041.11
Card                2789  1.737903e+08  24375382.31
Cash on Delivery    2315  1.360824e+08  19045631.70
Nagad               1849  1.166269e+08  16130491.45
Unknown               12  4.641756e+05     63119.87

In [45]:
payment_analysis = orders.groupby('Payment_Method').agg(
    Orders=('Order_ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
)

payment_analysis['Profit_Margin'] = (
    payment_analysis['Profit'] / payment_analysis['Sales'] * 100
)

payment_analysis.sort_values('Profit_Margin', ascending=False)

                  Orders         Sales       Profit  Profit_Margin
Payment_Method
Card                2789  1.737903e+08  24375382.31      14.025740
Cash on Delivery    2315  1.360824e+08  19045631.70      13.995657
bKash               3035  1.825643e+08  25369041.11      13.895947
Nagad               1849  1.166269e+08  16130491.45      13.830851
Unknown               12  4.641756e+05     63119.87      13.598273

In [46]:
customer_analysis = orders.groupby('Customer_ID').agg(
    Orders=('Order_ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
).sort_values('Sales', ascending=False)

customer_analysis.head(10)

             Orders       Sales     Profit
Customer_ID
CUST-0919        12  1715385.72  246122.61
CUST-1373        10  1635156.03  216555.42
CUST-0263         9  1479297.18  203118.28
CUST-1175        13  1406884.82  205029.01
CUST-0877        13  1399471.15  166547.44
CUST-0284         9  1353090.67  165064.30
CUST-0039        11  1352799.25  153966.15
CUST-1243         7  1350190.81  169418.30
CUST-1260        12  1344448.39  211116.57
CUST-1042        11  1318711.74  159496.03

In [47]:
customer_analysis['Customer_Segment'] = pd.qcut(
    customer_analysis['Sales'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value']
)

customer_analysis['Customer_Segment'].value_counts()

Customer_Segment
Low Value       500
Medium Value    499
High Value      499
Name: count, dtype: int64

In [50]:
segment_analysis = customer_analysis.groupby('Customer_Segment', observed=True).agg(
    Customers=('Orders', 'count'),
    Orders=('Orders', 'sum'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
)

segment_analysis['Profit_Margin'] = (
    segment_analysis['Profit'] / segment_analysis['Sales'] * 100
)

segment_analysis

                  Customers  Orders         Sales       Profit  Profit_Margin
Customer_Segment
Low Value               500    2472  6.785911e+07  11102593.89      16.361243
Medium Value            499    3451  1.785623e+08  25673017.80      14.377627
High Value              499    4077  3.631068e+08  48208054.75      13.276550

In [51]:
segment_analysis.sort_values('Sales', ascending=False)

                  Customers  Orders         Sales       Profit  Profit_Margin
Customer_Segment
High Value              499    4077  3.631068e+08  48208054.75      13.276550
Medium Value            499    3451  1.785623e+08  25673017.80      14.377627
Low Value               500    2472  6.785911e+07  11102593.89      16.361243

In [52]:
orders['Month'] = orders['Order_Date'].dt.to_period('M')

monthly_sales = orders.groupby('Month').agg(
    Orders=('Order_ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
).reset_index()

monthly_sales

      Month  Orders        Sales      Profit
0   2025-01     866  50646428.58  7067076.29
1   2025-02     768  42998654.65  6176986.19
2   2025-03     851  51314106.75  7232657.26
3   2025-04     812  51362895.95  7000997.41
4   2025-05     818  47896551.30  6827528.29
5   2025-06     796  47988446.70  6650825.11
6   2025-07     835  53446551.27  7310022.81
7   2025-08     882  51285261.38  7149687.29
8   2025-09     820  49997538.33  6932116.09
9   2025-10     864  53553557.37  7533901.35
10  2025-11     791  49957647.01  6897162.46
11  2025-12     897  59080537.53  8204705.89

In [53]:
product_analysis = orders.groupby('Product_ID').agg(
    Orders=('Order_ID', 'nunique'),
    Quantity=('Quantity', 'sum'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
).sort_values('Sales', ascending=False)

product_analysis.head(10)

            Orders  Quantity        Sales      Profit
Product_ID
PROD-052       120       285  27543559.65  4058807.29
PROD-018       114       267  26285657.25  2145239.06
PROD-013       102       236  24494033.67  2921493.41
PROD-054        88       225  23404954.63  3990019.89
PROD-077       101       257  23360138.28  2360708.58
PROD-008        92       243  23114759.86  2529230.34
PROD-050        97       221  21545569.02  2283028.84
PROD-088        98       219  16704552.07  2847718.03
PROD-078       108       260  15196765.62  1433729.51
PROD-090       108       275  14934407.04  2484701.85

In [54]:
product_analysis['Profit_Margin'] = (
    product_analysis['Profit'] / product_analysis['Sales'] * 100
)

product_analysis.sort_values(
    'Profit_Margin',
    ascending=False
).head(10)

            Orders  Quantity       Sales      Profit  Profit_Margin
Product_ID
PROD-037        90       195   503521.23   180028.01      35.753807
PROD-030       102       245   874549.72   304223.07      34.786252
PROD-070       109       279  3562224.70  1201783.43      33.736879
PROD-095        96       236   658299.40   220952.66      33.564159
PROD-036       103       255   424164.81   138071.41      32.551359
PROD-016        95       234  2161374.95   696709.95      32.234571
PROD-029        87       220  2477909.44   787887.69      31.796468
PROD-019       113       271  3403486.71  1064747.01      31.284007
PROD-087        95       238  1039494.46   319815.20      30.766417
PROD-097       112       270   649638.75   195760.39      30.133730

In [55]:
status_analysis = orders['Order_Status'].value_counts().to_frame('Orders')

status_analysis['Percentage'] = (
    status_analysis['Orders'] / len(orders) * 100
)

status_analysis

              Orders  Percentage
Order_Status
Delivered       9120       91.20
Cancelled        496        4.96
Returned         384        3.84

In [56]:
discount_analysis = orders.groupby('Discount').agg(
    Orders=('Order_ID', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Profit', 'sum')
).reset_index()

discount_analysis['Profit_Margin'] = (
    discount_analysis['Profit'] / discount_analysis['Sales'] * 100
)

discount_analysis

   Discount  Orders         Sales       Profit  Profit_Margin
0      0.00    3790  2.517556e+08  35218784.68      13.989278
1      0.05    2015  1.249099e+08  17672725.29      14.148376
2      0.10    2236  1.284571e+08  17560544.65      13.670353
3      0.15    1363  7.235675e+07  10057871.56      13.900392
4      0.20     596  3.204880e+07   4473740.26      13.959149

In [57]:
correlation = orders[['Discount', 'Sales', 'Profit']].corr()

correlation

          Discount     Sales    Profit
Discount  1.000000 -0.055165 -0.064134
Sales    -0.055165  1.000000  0.946568
Profit   -0.064134  0.946568  1.000000

In [60]:
analysis_date = orders['Order_Date'].max()

recency = orders.groupby('Customer_ID').agg(
    Last_Order_Date=('Order_Date', 'max')
).reset_index()

recency['Recency_Days'] = (
    analysis_date - recency['Last_Order_Date']
).dt.days

recency.head(10)

  Customer_ID Last_Order_Date  Recency_Days
0   CUST-0001      2025-10-20            72
1   CUST-0002      2025-12-07            24
2   CUST-0003      2025-12-30             1
3   CUST-0004      2025-10-26            66
4   CUST-0005      2025-12-15            16
5   CUST-0006      2025-12-16            15
6   CUST-0007      2025-09-29            93
7   CUST-0008      2025-09-17           105
8   CUST-0009      2025-12-28             3
9   CUST-0010      2025-11-14            47

In [61]:
frequency = orders.groupby('Customer_ID').agg(
    Frequency=('Order_ID', 'nunique')
).reset_index()

frequency.head(10)

  Customer_ID  Frequency
0   CUST-0001          3
1   CUST-0002          5
2   CUST-0003          4
3   CUST-0004          7
4   CUST-0005          8
5   CUST-0006          9
6   CUST-0007          6
7   CUST-0008          5
8   CUST-0009         12
9   CUST-0010          6

In [62]:
monetary = orders.groupby('Customer_ID').agg(
    Monetary=('Sales', 'sum')
).reset_index()

monetary.head(10)

  Customer_ID    Monetary
0   CUST-0001   141586.58
1   CUST-0002   313041.70
2   CUST-0003    42371.22
3   CUST-0004   266861.58
4   CUST-0005   474047.32
5   CUST-0006  1078923.31
6   CUST-0007   756485.90
7   CUST-0008   316449.56
8   CUST-0009   286777.26
9   CUST-0010   288792.65

In [63]:
rfm = recency.merge(
    frequency,
    on='Customer_ID'
).merge(
    monetary,
    on='Customer_ID'
)

rfm.head(10)

  Customer_ID Last_Order_Date  Recency_Days  Frequency    Monetary
0   CUST-0001      2025-10-20            72          3   141586.58
1   CUST-0002      2025-12-07            24          5   313041.70
2   CUST-0003      2025-12-30             1          4    42371.22
3   CUST-0004      2025-10-26            66          7   266861.58
4   CUST-0005      2025-12-15            16          8   474047.32
5   CUST-0006      2025-12-16            15          9  1078923.31
6   CUST-0007      2025-09-29            93          6   756485.90
7   CUST-0008      2025-09-17           105          5   316449.56
8   CUST-0009      2025-12-28             3         12   286777.26
9   CUST-0010      2025-11-14            47          6   288792.65

In [64]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency_Days'],
    q=5,
    labels=[5, 4, 3, 2, 1]
)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int).astype(str) +
    rfm['F_Score'].astype(int).astype(str) +
    rfm['M_Score'].astype(int).astype(str)
)

rfm.head(10)

,Customer_ID,Last_Order_Date,Recency_Days,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score
0,CUST-0001,2025-10-20,72,3,141586.58,2,1,1,211
1,CUST-0002,2025-12-07,24,5,313041.70,4,2,3,423
2,CUST-0003,2025-12-30,1,4,42371.22,5,1,1,511
3,CUST-0004,2025-10-26,66,7,266861.58,2,3,2,232
4,CUST-0005,2025-12-15,16,8,474047.32,4,4,4,444
5,CUST-0006,2025-12-16,15,9,1078923.31,4,4,5,445
6,CUST-0007,2025-09-29,93,6,756485.90,1,2,5,125
7,CUST-0008,2025-09-17,105,5,316449.56,1,2,3,123
8,CUST-0009,2025-12-28,3,12,286777.26,5,5,3,553
9,CUST-0010,2025-11-14,47,6,288792.65,3,2,3,323

In [65]:
def rfm_segment(row):
    r = row['R_Score']
    f = row['F_Score']
    m = row['M_Score']

    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New Customers'
    elif r <= 2 and f >= 3:
        return 'At Risk'
    elif r <= 2 and f <= 2:
        return 'Lost Customers'
    else:
        return 'Potential Customers'


rfm['Customer_Segment'] = rfm.apply(rfm_segment, axis=1)

rfm[['Customer_ID', 'RFM_Score', 'Customer_Segment']].head(10)

  Customer_ID RFM_Score     Customer_Segment
0   CUST-0001       211       Lost Customers
1   CUST-0002       423        New Customers
2   CUST-0003       511        New Customers
3   CUST-0004       232              At Risk
4   CUST-0005       444            Champions
5   CUST-0006       445            Champions
6   CUST-0007       125       Lost Customers
7   CUST-0008       123       Lost Customers
8   CUST-0009       553      Loyal Customers
9   CUST-0010       323  Potential Customers

In [66]:
rfm_segment_analysis = rfm.groupby('Customer_Segment').agg(
    Customers=('Customer_ID', 'nunique'),
    Orders=('Frequency', 'sum'),
    Sales=('Monetary', 'sum')
).reset_index()

rfm_segment_analysis['Avg_Sales_per_Customer'] = (
    rfm_segment_analysis['Sales'] /
    rfm_segment_analysis['Customers']
)

rfm_segment_analysis.sort_values(
    'Sales',
    ascending=False
)

,Customer_Segment,Customers,Orders,Sales,Avg_Sales_per_Customer
3,Loyal Customers,444,3522,1.925865e+08,433753.329144
1,Champions,188,1821,1.369466e+08,728439.101330
0,At Risk,267,2113,1.298183e+08,486210.982846
2,Lost Customers,323,1337,7.555240e+07,233908.348607
4,New Customers,170,751,4.771649e+07,280685.260529
5,Potential Customers,106,456,2.690792e+07,253848.342642

In [70]:
customer_analysis = customer_analysis.reset_index()

In [71]:
customer_analysis.columns

Index(['Customer_ID', 'Orders', 'Sales', 'Profit', 'Customer_Segment'], dtype='str')

In [72]:
rfm_profit_analysis = rfm.merge(
    customer_analysis[['Customer_ID', 'Profit']],
    on='Customer_ID',
    how='left'
)

segment_profit_analysis = rfm_profit_analysis.groupby(
    'Customer_Segment'
).agg(
    Customers=('Customer_ID', 'nunique'),
    Sales=('Monetary', 'sum'),
    Profit=('Profit', 'sum')
).reset_index()

segment_profit_analysis['Profit_Margin'] = (
    segment_profit_analysis['Profit'] /
    segment_profit_analysis['Sales'] * 100
)

segment_profit_analysis.sort_values(
    'Profit',
    ascending=False
)

      Customer_Segment  Customers         Sales       Profit  Profit_Margin
3      Loyal Customers        444  1.925865e+08  27405861.04      14.230418
1            Champions        188  1.369466e+08  18607050.99      13.587090
0              At Risk        267  1.298183e+08  17901059.50      13.789316
2       Lost Customers        323  7.555240e+07  10810720.88      14.308905
4        New Customers        170  4.771649e+07   6610499.00      13.853698
5  Potential Customers        106  2.690792e+07   3648475.03      13.559110

In [73]:
clv = orders.groupby('Customer_ID').agg(
    Orders=('Order_ID', 'nunique'),
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum')
).reset_index()

clv['Average_Order_Value'] = (
    clv['Total_Sales'] / clv['Orders']
)

clv['Profit_Margin'] = (
    clv['Total_Profit'] / clv['Total_Sales'] * 100
)

clv.sort_values(
    'Total_Sales',
    ascending=False
).head(10)

,Customer_ID,Orders,Total_Sales,Total_Profit,Average_Order_Value,Profit_Margin
918,CUST-0919,12,1715385.72,246122.61,142948.810000,14.347946
1370,CUST-1373,10,1635156.03,216555.42,163515.603000,13.243716
262,CUST-0263,9,1479297.18,203118.28,164366.353333,13.730729
1173,CUST-1175,13,1406884.82,205029.01,108221.909231,14.573262
876,CUST-0877,13,1399471.15,166547.44,107651.626923,11.900741
283,CUST-0284,9,1353090.67,165064.30,150343.407778,12.199057
38,CUST-0039,11,1352799.25,153966.15,122981.750000,11.381301
1240,CUST-1243,7,1350190.81,169418.30,192884.401429,12.547730
1257,CUST-1260,12,1344448.39,211116.57,112037.365833,15.702839
1041,CUST-1042,11,1318711.74,159496.03,119882.885455,12.094837

In [74]:
clv['Customer_Value_Segment'] = pd.qcut(
    clv['Total_Sales'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value']
)

clv['Customer_Value_Segment'].value_counts()

Customer_Value_Segment
Low Value       500
Medium Value    499
High Value      499
Name: count, dtype: int64

In [75]:
customer_value_analysis = clv.groupby(
    'Customer_Value_Segment',
    observed=True
).agg(
    Customers=('Customer_ID', 'nunique'),
    Orders=('Orders', 'sum'),
    Sales=('Total_Sales', 'sum'),
    Profit=('Total_Profit', 'sum')
).reset_index()

customer_value_analysis['Avg_Sales_per_Customer'] = (
    customer_value_analysis['Sales'] /
    customer_value_analysis['Customers']
)

customer_value_analysis['Profit_Margin'] = (
    customer_value_analysis['Profit'] /
    customer_value_analysis['Sales'] * 100
)

customer_value_analysis.sort_values(
    'Sales',
    ascending=False
)

,Customer_Value_Segment,Customers,Orders,Sales,Profit,Avg_Sales_per_Customer,Profit_Margin
2,High Value,499,4077,3.631068e+08,48208054.75,727668.926012,13.276550
1,Medium Value,499,3451,1.785623e+08,25673017.80,357840.222946,14.377627
0,Low Value,500,2472,6.785911e+07,11102593.89,135718.222980,16.361243

In [76]:
executive_kpi = {
    'Total Orders': orders['Order_ID'].nunique(),
    'Total Customers': orders['Customer_ID'].nunique(),
    'Total Sales': orders['Sales'].sum(),
    'Total Profit': orders['Profit'].sum(),
    'Average Order Value': orders['Sales'].sum() / orders['Order_ID'].nunique(),
    'Profit Margin': orders['Profit'].sum() / orders['Sales'].sum() * 100,
    'Delivery Rate': (orders['Order_Status'].eq('Delivered').sum() / len(orders)) * 100,
    'Cancellation Rate': (orders['Order_Status'].eq('Cancelled').sum() / len(orders)) * 100,
    'Return Rate': (orders['Order_Status'].eq('Returned').sum() / len(orders)) * 100
}

executive_kpi

{'Total Orders': 10000,
 'Total Customers': 1498,
 'Total Sales': np.float64(609528176.8199999),
 'Total Profit': np.float64(84983666.44),
 'Average Order Value': np.float64(60952.81768199999),
 'Profit Margin': np.float64(13.94253287573555),
 'Delivery Rate': np.float64(91.2),
 'Cancellation Rate': np.float64(4.96),
 'Return Rate': np.float64(3.84)}

In [77]:
business_summary = {
    'Highest Sales Month': monthly_sales.loc[
        monthly_sales['Sales'].idxmax(), 'Month'
    ],

    'Highest Monthly Sales': monthly_sales['Sales'].max(),

    'Lowest Sales Month': monthly_sales.loc[
        monthly_sales['Sales'].idxmin(), 'Month'
    ],

    'Lowest Monthly Sales': monthly_sales['Sales'].min(),

    'Top Product': product_analysis.index[0],

    'Top Product Sales': product_analysis.iloc[0]['Sales'],

    'Top Customer': customer_analysis.sort_values(
        'Sales', ascending=False
    ).iloc[0]['Customer_ID'],

    'Top Customer Sales': customer_analysis.sort_values(
        'Sales', ascending=False
    ).iloc[0]['Sales'],

    'Top Payment Method': orders['Payment_Method'].value_counts().index[0]
}

business_summary

{'Highest Sales Month': Period('2025-12', 'M'),
 'Highest Monthly Sales': np.float64(59080537.53),
 'Lowest Sales Month': Period('2025-02', 'M'),
 'Lowest Monthly Sales': np.float64(42998654.65),
 'Top Product': 'PROD-052',
 'Top Product Sales': np.float64(27543559.650000002),
 'Top Customer': 'CUST-0919',
 'Top Customer Sales': np.float64(1715385.7200000002),
 'Top Payment Method': 'bKash'}

In [4]:
import pandas as pd

orders = pd.read_excel('Customer_Sales_Intelligence_Dataset.xlsx')

In [5]:
orders.head()

  Customer_ID  Customer_Name Customer_Segment      Region Signup_Date
0   CUST-0001  Customer 0001        Corporate      Khulna  2024-11-09
1   CUST-0002  Customer 0002         Consumer  Mymensingh  2025-06-27
2   CUST-0003  Customer 0003   Small Business  Chattogram  2024-12-02
3   CUST-0004  Customer 0004        Corporate  Chattogram  2024-10-13
4   CUST-0005  Customer 0005         Consumer    Barishal  2024-05-27

In [6]:
import pandas as pd

excel_file = pd.ExcelFile('Customer_Sales_Intelligence_Dataset.xlsx')

excel_file.sheet_names

['Customers', 'Products', 'Orders', 'Data_Dictionary', 'Project_Notes']

In [7]:
orders = pd.read_excel(
    'Customer_Sales_Intelligence_Dataset.xlsx',
    sheet_name='Orders'
)

orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Discount,Sales,Profit,Payment_Method,Order_Status
0,ORD-100001,2025-10-17,CUST-0662,PROD-048,5,0.00,16624.85,5083.99,Nagad,Delivered
1,ORD-100002,2025-04-21,CUST-1425,PROD-009,2,0.20,7495.87,1845.95,Cash on Delivery,Delivered
2,ORD-100003,2025-05-19,CUST-0272,PROD-039,4,0.05,94402.49,21615.55,Card,Delivered
3,ORD-100004,2025-11-02,CUST-1004,PROD-059,1,0.00,4184.55,1013.89,Nagad,Delivered
4,ORD-100005,2025-06-25,CUST-0269,PROD-003,4,0.20,88857.95,13593.28,Card,Delivered

In [8]:
orders.to_csv(
    'Customer_Sales_Intelligence_cleaned.csv',
    index=False
)

In [9]:
import os

os.path.exists('Customer_Sales_Intelligence_cleaned.csv')

True

In [1]:
import os

os.path.abspath('Customer_Sales_Intelligence_cleaned.csv')

'C:\\Users\\MY PC\\Desktop\\Customer_Sales_Intelligence\\Customer_Sales_Intelligence_cleaned.csv'

In [5]:
import pandas as pd

In [7]:
import os
os.getcwd()

'C:\\Users\\MY PC\\Desktop\\Customer_Sales_Intelligence'

In [8]:
import os

os.listdir()

['.ipynb_checkpoints',
 'Customer_Sales_Intelligence.ipynb',
 'Customer_Sales_Intelligence.pbix',
 'Customer_Sales_Intelligence_cleaned.xlsx']

In [10]:
pd.ExcelFile("Customer_Sales_Intelligence_cleaned.xlsx").sheet_names

['Customer_Sales_Intelligence_cle']

In [11]:
orders = pd.read_excel(
    "Customer_Sales_Intelligence_cleaned.xlsx",
    sheet_name="Customer_Sales_Intelligence_cle"
)

In [12]:
orders.shape

(10000, 10)

In [13]:
analysis_date = orders['Order_Date'].max()

recency = orders.groupby('Customer_ID').agg(
    Last_Order_Date=('Order_Date', 'max')
).reset_index()

recency['Recency_Days'] = (
    analysis_date - recency['Last_Order_Date']
).dt.days

frequency = orders.groupby('Customer_ID').agg(
    Frequency=('Order_ID', 'nunique')
).reset_index()

monetary = orders.groupby('Customer_ID').agg(
    Monetary=('Sales', 'sum')
).reset_index()

rfm = (
    recency
    .merge(frequency, on='Customer_ID')
    .merge(monetary, on='Customer_ID')
)

rfm.head()

  Customer_ID Last_Order_Date  Recency_Days  Frequency   Monetary
0   CUST-0001      2025-10-20            72          3  141586.58
1   CUST-0002      2025-12-07            24          5  313041.70
2   CUST-0003      2025-12-30             1          4   42371.22
3   CUST-0004      2025-10-26            66          7  266861.58
4   CUST-0005      2025-12-15            16          8  474047.32

In [14]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency_Days'],
    q=5,
    labels=[5, 4, 3, 2, 1]
)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int).astype(str) +
    rfm['F_Score'].astype(int).astype(str) +
    rfm['M_Score'].astype(int).astype(str)
)

rfm.head()

,Customer_ID,Last_Order_Date,Recency_Days,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score
0,CUST-0001,2025-10-20,72,3,141586.58,2,1,1,211
1,CUST-0002,2025-12-07,24,5,313041.70,4,2,3,423
2,CUST-0003,2025-12-30,1,4,42371.22,5,1,1,511
3,CUST-0004,2025-10-26,66,7,266861.58,2,3,2,232
4,CUST-0005,2025-12-15,16,8,474047.32,4,4,4,444

In [15]:
def rfm_segment(row):
    r = row['R_Score']
    f = row['F_Score']
    m = row['M_Score']

    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New Customers'
    elif r <= 2 and f >= 3:
        return 'At Risk'
    elif r <= 2 and f <= 2:
        return 'Lost Customers'
    else:
        return 'Potential Customers'

rfm['Customer_Segment'] = rfm.apply(rfm_segment, axis=1)

rfm[['Customer_ID', 'RFM_Score', 'Customer_Segment']].head()

  Customer_ID RFM_Score Customer_Segment
0   CUST-0001       211   Lost Customers
1   CUST-0002       423    New Customers
2   CUST-0003       511    New Customers
3   CUST-0004       232          At Risk
4   CUST-0005       444        Champions

In [2]:
import pandas as pd

orders = pd.read_excel(
    "Customer_Sales_Intelligence_cleaned.xlsx",
    sheet_name="Customer_Sales_Intelligence_cle"
)

In [3]:
analysis_date = orders['Order_Date'].max()

recency = orders.groupby('Customer_ID').agg(
    Last_Order_Date=('Order_Date', 'max')
).reset_index()

recency['Recency_Days'] = (
    analysis_date - recency['Last_Order_Date']
).dt.days

frequency = orders.groupby('Customer_ID').agg(
    Frequency=('Order_ID', 'nunique')
).reset_index()

monetary = orders.groupby('Customer_ID').agg(
    Monetary=('Sales', 'sum')
).reset_index()

rfm = (
    recency
    .merge(frequency, on='Customer_ID')
    .merge(monetary, on='Customer_ID')
)

rfm.head()

  Customer_ID Last_Order_Date  Recency_Days  Frequency   Monetary
0   CUST-0001      2025-10-20            72          3  141586.58
1   CUST-0002      2025-12-07            24          5  313041.70
2   CUST-0003      2025-12-30             1          4   42371.22
3   CUST-0004      2025-10-26            66          7  266861.58
4   CUST-0005      2025-12-15            16          8  474047.32

In [4]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency_Days'],
    q=5,
    labels=[5, 4, 3, 2, 1]
)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int).astype(str) +
    rfm['F_Score'].astype(int).astype(str) +
    rfm['M_Score'].astype(int).astype(str)
)

rfm[['Customer_ID', 'R_Score', 'F_Score', 'M_Score', 'RFM_Score']].head()

  Customer_ID R_Score F_Score M_Score RFM_Score
0   CUST-0001       2       1       1       211
1   CUST-0002       4       2       3       423
2   CUST-0003       5       1       1       511
3   CUST-0004       2       3       2       232
4   CUST-0005       4       4       4       444

In [5]:
def rfm_segment(row):
    r = row['R_Score']
    f = row['F_Score']
    m = row['M_Score']

    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New Customers'
    elif r <= 2 and f >= 3:
        return 'At Risk'
    elif r <= 2 and f <= 2:
        return 'Lost Customers'
    else:
        return 'Potential Customers'

rfm['Customer_Segment'] = rfm.apply(rfm_segment, axis=1)

rfm[['Customer_ID', 'RFM_Score', 'Customer_Segment']].head()

  Customer_ID RFM_Score Customer_Segment
0   CUST-0001       211   Lost Customers
1   CUST-0002       423    New Customers
2   CUST-0003       511    New Customers
3   CUST-0004       232          At Risk
4   CUST-0005       444        Champions

In [6]:
rfm.to_csv("RFM_Customer_Segments.csv", index=False)

In [2]:
import pandas as pd

orders = pd.read_excel(
    "Customer_Sales_Intelligence_cleaned.xlsx",
    sheet_name="Customer_Sales_Intelligence_cle"
)

In [3]:
analysis_date = orders['Order_Date'].max()

recency = orders.groupby('Customer_ID').agg(
    Last_Order_Date=('Order_Date', 'max')
).reset_index()

recency['Recency_Days'] = (
    analysis_date - recency['Last_Order_Date']
).dt.days

frequency = orders.groupby('Customer_ID').agg(
    Frequency=('Order_ID', 'nunique')
).reset_index()

monetary = orders.groupby('Customer_ID').agg(
    Monetary=('Sales', 'sum')
).reset_index()

rfm = (
    recency
    .merge(frequency, on='Customer_ID')
    .merge(monetary, on='Customer_ID')
)

rfm.head()

  Customer_ID Last_Order_Date  Recency_Days  Frequency   Monetary
0   CUST-0001      2025-10-20            72          3  141586.58
1   CUST-0002      2025-12-07            24          5  313041.70
2   CUST-0003      2025-12-30             1          4   42371.22
3   CUST-0004      2025-10-26            66          7  266861.58
4   CUST-0005      2025-12-15            16          8  474047.32

In [4]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency_Days'],
    q=5,
    labels=[5, 4, 3, 2, 1]
)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int).astype(str) +
    rfm['F_Score'].astype(int).astype(str) +
    rfm['M_Score'].astype(int).astype(str)
)

def rfm_segment(row):
    r = row['R_Score']
    f = row['F_Score']
    m = row['M_Score']

    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New Customers'
    elif r <= 2 and f >= 3:
        return 'At Risk'
    elif r <= 2 and f <= 2:
        return 'Lost Customers'
    else:
        return 'Potential Customers'

rfm['Customer_Segment'] = rfm.apply(rfm_segment, axis=1)

rfm['Value_Segment'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value']
)

rfm[
    ['Customer_ID', 'RFM_Score', 'Customer_Segment',
     'Monetary', 'Value_Segment']
].head()

  Customer_ID RFM_Score Customer_Segment   Monetary Value_Segment
0   CUST-0001       211   Lost Customers  141586.58     Low Value
1   CUST-0002       423    New Customers  313041.70  Medium Value
2   CUST-0003       511    New Customers   42371.22     Low Value
3   CUST-0004       232          At Risk  266861.58  Medium Value
4   CUST-0005       444        Champions  474047.32  Medium Value

In [2]:
import pandas as pd

# Load data
orders = pd.read_excel(
    "Customer_Sales_Intelligence_cleaned.xlsx",
    sheet_name="Customer_Sales_Intelligence_cle"
)

# Analysis date
analysis_date = orders['Order_Date'].max()

# Recency
recency = orders.groupby('Customer_ID').agg(
    Last_Order_Date=('Order_Date', 'max')
).reset_index()

recency['Recency_Days'] = (
    analysis_date - recency['Last_Order_Date']
).dt.days

# Frequency
frequency = orders.groupby('Customer_ID').agg(
    Frequency=('Order_ID', 'nunique')
).reset_index()

# Monetary
monetary = orders.groupby('Customer_ID').agg(
    Monetary=('Sales', 'sum')
).reset_index()

# Build RFM table
rfm = (
    recency
    .merge(frequency, on='Customer_ID')
    .merge(monetary, on='Customer_ID')
)

# RFM Scores
rfm['R_Score'] = pd.qcut(
    rfm['Recency_Days'],
    q=5,
    labels=[5, 4, 3, 2, 1]
)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=5,
    labels=[1, 2, 3, 4, 5]
)

# RFM Score
rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int).astype(str) +
    rfm['F_Score'].astype(int).astype(str) +
    rfm['M_Score'].astype(int).astype(str)
)

# Customer Segment
def rfm_segment(row):
    r = row['R_Score']
    f = row['F_Score']
    m = row['M_Score']

    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New Customers'
    elif r <= 2 and f >= 3:
        return 'At Risk'
    elif r <= 2 and f <= 2:
        return 'Lost Customers'
    else:
        return 'Potential Customers'

rfm['Customer_Segment'] = rfm.apply(rfm_segment, axis=1)

# Customer Value Segment
rfm['Value_Segment'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value']
)

# Save updated CSV
rfm.to_csv("RFM_Customer_Segments.csv", index=False)

# Check
print(rfm.columns.tolist())

['Customer_ID', 'Last_Order_Date', 'Recency_Days', 'Frequency', 'Monetary', 'R_Score', 'F_Score', 'M_Score', 'RFM_Score', 'Customer_Segment', 'Value_Segment']

In [3]:
value_segment = rfm[['Customer_ID', 'Value_Segment']].copy()

value_segment.to_csv(
    "Customer_Value_Segments.csv",
    index=False
)